### ISSUE TITLE
scATAC peak file

### ISSUE THREAD

**Issue by mvinyard** [GreenleafLab/MPAL-Single-Cell-2019#1]
Hi there,

Just wondering if there is a scATAC peak file associated with the published data set that could be used for reference? 

Thanks!

**Comment by jgranja24** [comment]
Yes! If you download the scATAC-seq summarized experiment (for hematopoiesis or hematopoiesis + MPAL) and use rowRanges(se) it will return the peaks.

**Comment by mvinyard** [comment]
Great, thank you!
