### ISSUE TITLE
Download link does not match with the description

### ISSUE THREAD

**Issue by ptdtan** [GreenleafLab/MPAL-Single-Cell-2019#3]
Dear authors,
In the README, the download link for scRNA-Seq data of Healthy Hematopoiesis, which has **scATAC** in its name, does not match with its description, scRNA-seq. Could you please check it ?

**scRNA-seq Hematopoeisis cell x gene Summarized Experiment** :
https://jeffgranja.s3.amazonaws.com/MPAL-10x/Supplementary_Data/Healthy-Data/scATAC-Cicero-GA-Hematopoiesis-191120.rds

Many thanks

**Comment by jgranja24** [comment]
sorry its fixed


scRNA-seq Hematopoeisis cell x gene Summarized Experiment :
https://jeffgranja.s3.amazonaws.com/MPAL-10x/Supplementary_Data/Healthy-Data/scRNA-Healthy-Hematopoiesis-191120.rds
