### ISSUE TITLE
Seurat v3

### ISSUE THREAD

**Issue by edward130603** [GreenleafLab/MPAL-Single-Cell-2019#5]
Several functions do not work with Seurat v3. Will the code provided be maintained for compatibility with Seurat v3?

**Comment by jgranja24** [comment]
I think this should work for seurat v3, let me know.

seuratSNN <- function(matSVD, dims.use = 1:50, ...){
    set.seed(1)
    message("Making Seurat Object...")
    tmp <- matrix(rnorm(nrow(matSVD) * 3, 10), ncol = nrow(matSVD), nrow = 3)
    colnames(tmp) <- rownames(matSVD)
    rownames(tmp) <- paste0("t",seq_len(nrow(tmp)))
    obj <- Seurat::CreateSeuratObject(tmp, project='scATAC', min.cells=0, min.features=0)
    obj[['pca']] <- Seurat::CreateDimReducObject(embeddings=mat, key='PC_', assay='RNA')
    clustParams <- list()
    clustParams$object <- obj
    clustParams$reduction <- "pca"
    clustParams$object <- suppressWarnings(do.call(Seurat::FindNeighbors, clustParams))
    obj <- suppressWarnings(do.call(Seurat::FindClusters, clustParams))
    #Get Output
    clust <- obj@meta.data[,ncol(obj@meta.data)]
    clust <- paste0("Cluster",match(clust, unique(clust)))
    names(clust) <- rownames(mat)
    clust
}

**Comment by mohit1997** [comment]
Edit

```R
seuratSNN <- function(matSVD, dims.use = 1:50, ...){
set.seed(1)
message("Making Seurat Object...")
tmp <- matrix(rnorm(nrow(matSVD) * 3, 10), ncol = nrow(matSVD), nrow = 3)
colnames(tmp) <- rownames(matSVD)
rownames(tmp) <- paste0("t",seq_len(nrow(tmp)))
obj <- Seurat::CreateSeuratObject(tmp, project='scATAC', min.cells=0, min.features=0)
obj[['pca']] <- Seurat::CreateDimReducObject(embeddings=matSVD, key='PC_', assay='RNA')
clustParams <- list()
clustParams$object <- obj
clustParams$reduction <- "pca"
clustParams$object <- suppressWarnings(do.call(Seurat::FindNeighbors, clustParams))
obj <- suppressWarnings(do.call(Seurat::FindClusters, clustParams))
#Get Output
clust <- obj@meta.data[,ncol(obj@meta.data)]
clust <- paste0("Cluster",match(clust, unique(clust)))
names(clust) <- rownames(matSVD)
clust
}
```
