### ISSUE TITLE
is there a way to combine different 10x results ie different fragment.tsv.gz? thanks!

### ISSUE THREAD

**Issue by hjack123** [GreenleafLab/MPAL-Single-Cell-2019#7]

**Comment by hjack123** [comment]
Hi can you please briefly describe how you integrated different scATAC datasets? if simply combining fragment files may encounter batch effect and how did you solve the problem. really much appreciated!!

**Comment by jgranja24** [comment]
Our iterativeLSI approach tries to minimize batch effects. No i did not combine fragment files into one I ran the code and merged matrices
