### ISSUE TITLE
error in 02.R...

### ISSUE THREAD

**Issue by hjack123** [GreenleafLab/MPAL-Single-Cell-2019#8]
Making Seurat Object...
 Error in CreateAssayObject(counts = counts, min.cells = min.cells, min.features = min.features) : 
  No feature names (rownames) names present in the input matrix

**Comment by hjack123** [comment]
Hi Whats the best alternative for SetDimReduction?

**Comment by hjack123** [comment]
mat <- mat[1:100,] + 1


why do we only include 100 features?

**Comment by jgranja24** [comment]
Sorry this is because i worked with Seurat 2.3.4 and you are using v3.
mat is just a random matrix it doesnt do anything.

Best
